task:
  container:
    image: ubuntu:latest
  name: Julia Test
  artifacts_cache:
    folder: ~/.julia/artifacts
  env:
    matrix:
      - JULIA_VERSION: 1.9
      - JULIA_VERSION: 1
      - JULIA_VERSION: nightly
  allow_failures: $JULIA_VERSION == 'nightly'
  install_script:
    - apt-get update && apt-get install -y curl
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
  coverage_script:
    - cirrusjl coverage codecov